Repository pagopa/pagopa-receipt-pdf-service, pull requests merged in 2023-09, with the labels that each got.

#40 [PRDP-133] fix: Logging configuration
  .env.example
  README.md
  helm/values-prod.yaml
  pom.xml
  src/main/resources/__logback.xml
  src/main/resources/application.properties
Labels: bug, patch, size/small

#39 [PRDP-123] feat: Use deployment selfhosted runner for integration test action
  .github/workflows/integration_test.yml
  performance-test/src/DockerfilePre
Labels: size/small, skip

#41 [PRDP-135] Added receipt's timestamps
  src/main/java/it/gov/pagopa/receipt/pdf/service/model/Receipt.java
Labels: enhancement, minor, size/small

#42 feat: Decrease max replica in UAT chart
  helm/values-uat.yaml
Labels: enhancement, size/small, skip

#45 fix: Dash Pipe
  .github/workflows/create_dashboard.yml
  .opex/env/dev/backend.ini
  .opex/env/dev/backend.tfvars
  .opex/env/dev/config.yaml
  .opex/env/dev/terraform.tfvars
  .opex/env/uat/config.yaml
Labels: size/small

#46 [PRDP-25] fix: Create dashboard action
  .github/workflows/create_dashboard.yml
  .identity/00_data.tf
  .identity/02_application_main.tf
  .identity/02_application_main_auth.tf
  .opex/pdf-receipt-service/env/prod/backend.ini
  .opex/pdf-receipt-service/env/prod/backend.tfvars
  .opex/pdf-receipt-service/env/prod/config.yaml
  .opex/pdf-receipt-service/env/prod/terraform.tfvars
  .opex/pdf-receipt-service/env/uat/backend.ini
  .opex/pdf-receipt-service/env/uat/backend.tfvars
  .opex/pdf-receipt-service/env/uat/config.yaml
  .opex/pdf-receipt-service/env/uat/terraform.tfvars
Labels: size/small
