Repository pagopa/pagopa-receipt-pdf-service, pull requests merged in 2023-08, with the labels that each got.

#13 fix: Identity
  .identity/02_application_action.tf
Labels: size/small

#12 [PRDP-85] fix: Status info response
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/resources/application.properties
Labels: bug, patch, size/small

#15 [PRDP-85] fix: Remove gc option
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: bug, patch, size/small

#16 fix: deploy
  src/main/resources/application.properties
Labels: patch

#17 [PRDP-85] fix: Deploy
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/resources/application.properties
Labels: bug, patch, size/small

#18 [PRDP-85] fix: Removed G1 gc option
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: bug, patch, size/small

#14 [PRDP-95] Introducing APM elk agent and logback.xml
  Dockerfile
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/resources/__logback.xml
  src/main/resources/application.properties
Labels: patch, size/small

#20 fix: Otel deploy
  Dockerfile
  helm/values-dev.yaml
Labels: patch, size/small

#22 fix: Otel
  Dockerfile
Labels: patch, size/small

#23 fix: Otel
  helm/values-dev.yaml
Labels: patch, size/small

#19 [PRDP-96] fix: Adjsut io error response
  integration-test/src/step_definitions/support/receipt_pdf_service_step.js
  openapi/generate_openapi.sh
  openapi/openapi.json
  src/main/java/it/gov/pagopa/receipt/pdf/service/App.java
  src/main/java/it/gov/pagopa/receipt/pdf/service/exception/mapper/ExceptionMapper.java
  src/main/java/it/gov/pagopa/receipt/pdf/service/model/ErrorMessage.java
  src/main/java/it/gov/pagopa/receipt/pdf/service/model/ErrorResponse.java
  src/test/java/it/gov/pagopa/receipt/pdf/service/resource/AttachmentResourceTest.java
Labels: bug, patch

#25 fix: Perf pipe
  .devops/performance-test-pipelines.yml
Labels: patch, size/small

#26 fix: Dev deploy
  helm/values-dev.yaml
  helm/values-uat.yaml
Labels: patch, size/small

#28 [PRDP-109] fix: Fix fiscal code checks
  src/main/java/it/gov/pagopa/receipt/pdf/service/enumeration/AppErrorCodeEnum.java
  src/main/java/it/gov/pagopa/receipt/pdf/service/service/impl/AttachmentsServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/service/service/impl/AttachmentsServiceImplTest.java
Labels: bug, patch, size/small

#30 [PRDP-116] fix: Improved fiscal code checks
  integration-test/src/features/receipt_pdf_service.feature
  src/main/java/it/gov/pagopa/receipt/pdf/service/enumeration/AppErrorCodeEnum.java
  src/main/java/it/gov/pagopa/receipt/pdf/service/exception/InvalidFiscalCodeHeaderException.java
  src/main/java/it/gov/pagopa/receipt/pdf/service/exception/mapper/ExceptionMapper.java
  src/main/java/it/gov/pagopa/receipt/pdf/service/resource/AttachmentResource.java
  src/test/java/it/gov/pagopa/receipt/pdf/service/resource/AttachmentResourceTest.java
Labels: bug, patch, size/small

#31 feat: Review request-limit aks
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: patch, size/small

#32 [PRDP-117] feat: Add slack webhook to integration tests action
  .github/workflows/integration_test.yml
  .identity/00_data.tf
  .identity/03_github_environment.tf
Labels: enhancement, minor, size/small

#33 fix: Slack notify
  .github/workflows/integration_test.yml
Labels: size/small

#34 fix integration test
  .github/workflows/integration_test.yml
Labels: bug, size/small, skip

#35 fix action
  .github/workflows/integration_test.yml
Labels: bug, size/small, skip

#36 fix action and cron
  .github/workflows/integration_test.yml
Labels: bug, size/small, skip

#37 fix cron
  .github/workflows/integration_test.yml
Labels: bug, size/small, skip

#38 fix: Test constant
  performance-test/src/test-types/constant.json
Labels: size/small
