Repository pagopa/pagopa-receipt-pdf-service, pull requests merged in 2023-11, with the labels that each got.

#53 [PRDP-188] feat: introducing tokenizer
  .devops/performance-test-pipelines.yml
  .env.example
  .github/workflows/code_review.yml
  .github/workflows/integration_test.yml
  .identity/00_data.tf
  .identity/03_github_environment.tf
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  integration-test/run_integration_test.sh
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.local
  integration-test/src/config/.env.prod
  integration-test/src/config/.env.uat
  integration-test/src/step_definitions/support/common.js
  integration-test/src/step_definitions/support/receipt_pdf_service_step.js
  integration-test/src/step_definitions/support/receipts_datastore_client.js
  performance-test/src/dev.environment.json
  performance-test/src/local.environment.json
  performance-test/src/package.json
  performance-test/src/scripts/README.md
  performance-test/src/scripts/scripts_common.js
  performance-test/src/uat.environment.json
  pom.xml
  src/main/java/it/gov/pagopa/receipt/pdf/service/client/PDVTokenizerClient.java
  src/main/java/it/gov/pagopa/receipt/pdf/service/exception/PDVTokenizerClientException.java
  src/main/java/it/gov/pagopa/receipt/pdf/service/exception/TooManyRequestsException.java
  src/main/java/it/gov/pagopa/receipt/pdf/service/model/SearchTokenRequest.java
  src/main/java/it/gov/pagopa/receipt/pdf/service/model/SearchTokenResponse.java
  src/main/java/it/gov/pagopa/receipt/pdf/service/service/impl/AttachmentsServiceImpl.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/receipt/pdf/service/client/PDVTokenizerClientTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/service/service/impl/AttachmentsServiceImplTest.java
Labels: minor, size/large

#54 fix: updated pdfs-700 on missing token to add stacktrace in the error…
  integration-test/src/step_definitions/support/receipt_pdf_service_step.js
  src/main/java/it/gov/pagopa/receipt/pdf/service/service/impl/AttachmentsServiceImpl.java
Labels: patch, size/small

#55 [fix] Fixed tokenizer path in prod
  helm/values-prod.yaml
Labels: size/small

#57 [PRDP-235] feat: Add pod antiAffinity
  helm/values-prod.yaml
Labels: size/small
