Repository pagopa/pagopa-receipt-pdf-service, pull requests merged in 2023-10, with the labels that each got.

#49 fix: Dash prod
  .opex/pdf-receipt-service/env/prod/config.yaml
Labels: size/small

#50 [PRDP-159] Deleted fiscal code from logs
  src/main/java/it/gov/pagopa/receipt/pdf/service/resource/AttachmentResource.java
  src/main/java/it/gov/pagopa/receipt/pdf/service/service/impl/AttachmentsServiceImpl.java
Labels: enhancement, size/large, patch

#51 [PRDP-164] feat: Added specific section for payer error in receipt
  src/main/java/it/gov/pagopa/receipt/pdf/service/model/receipt/Receipt.java
Labels: patch, size/small

#52 [PRDP-172] feat: Add application insights agent
  .github/maven_code_review/action.yml
  Dockerfile
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: enhancement, minor, size/small
