Repository pagopa/pagopa-receipt-pdf-service, pull requests merged in 2023-07, with the labels that each got.

#1 [PRDP-18] feat: Add receipt pdf service
  .github/workflows/code_review.yml
  .github/workflows/release_deploy.yml
  .gitignore
  Dockerfile
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/docker/Dockerfile.jvm
  src/main/docker/Dockerfile.legacy-jar
  src/main/docker/Dockerfile.native
  src/main/docker/Dockerfile.native-micro
  src/main/java/it/gov/pagopa/receipt/pdf/service/App.java
  src/main/java/it/gov/pagopa/receipt/pdf/service/client/ReceiptBlobClient.java
  src/main/java/it/gov/pagopa/receipt/pdf/service/client/impl/ReceiptBlobClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/service/client/impl/ReceiptCosmosClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/service/enumeration/AppErrorCodeEnum.java
  src/main/java/it/gov/pagopa/receipt/pdf/service/exception/AttachmentNotFoundException.java
  src/main/java/it/gov/pagopa/receipt/pdf/service/exception/MissingFiscalCodeHeaderException.java
  src/main/java/it/gov/pagopa/receipt/pdf/service/exception/ReceiptNotFoundException.java
  src/main/java/it/gov/pagopa/receipt/pdf/service/exception/mapper/ExceptionMapper.java
  src/main/java/it/gov/pagopa/receipt/pdf/service/producer/CosmosClientProducer.java
  src/main/java/it/gov/pagopa/receipt/pdf/service/resource/AttachmentResource.java
  src/main/java/it/gov/pagopa/receipt/pdf/service/service/AttachmentsService.java
  src/main/java/it/gov/pagopa/receipt/pdf/service/service/impl/AttachmentsServiceImpl.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/receipt/pdf/service/client/impl/ReceiptBlobClientImplTest.java
Labels: enhancement, minor, size/large

#5 Fix
  README.md
  src/test/java/it/gov/pagopa/receipt/pdf/service/resource/AttachmentResourceTest.java
Labels: bug, patch, size/small

#6 [PRDP-69 ] fix: Sonar smell and coverage
  .github/maven_code_review/action.yml
  .github/workflows/code_review.yml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/receipt/pdf/service/client/impl/ReceiptBlobClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/service/model/InfoResponse.java
  src/main/java/it/gov/pagopa/receipt/pdf/service/resource/AttachmentResource.java
  src/main/java/it/gov/pagopa/receipt/pdf/service/resource/InfoResource.java
  src/main/java/it/gov/pagopa/receipt/pdf/service/service/impl/AttachmentsServiceImpl.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/receipt/pdf/service/resource/InfoResourceTest.java
Labels: bug, patch, size/small

#8 fix: Fiscal code param
  openapi/openapi.json
  src/main/java/it/gov/pagopa/receipt/pdf/service/resource/AttachmentResource.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/receipt/pdf/service/resource/AttachmentResourceTest.java
Labels: bug, patch, size/small

#11 fix: Gha runner
  .github/workflows/deploy_with_github_runner.yml
Labels: size/small
